# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-03 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('salary', models.IntegerField(verbose_name='工资')),
                ('province', models.CharField(max_length=32, verbose_name='省份')),
                ('dept', models.CharField(max_length=32, verbose_name='部门')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'employee',
            },
        ),
    ]
